//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lost_And_Found.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LostandFoundEntities1 : DbContext
    {
        public LostandFoundEntities1()
            : base("name=LostandFoundEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<App_Admin> App_Admin { get; set; }
        public virtual DbSet<App_User> App_User { get; set; }
        public virtual DbSet<Found_Product> Found_Product { get; set; }
        public virtual DbSet<Lost_Product> Lost_Product { get; set; }
        public virtual DbSet<Product> Products { get; set; }
    }
}
